# Generated by Django 3.2 on 2021-04-21 07:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='LiveMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Name')),
                ('full_name', models.CharField(max_length=100, verbose_name='Full name')),
                ('phone', models.CharField(max_length=100, verbose_name='Phone')),
                ('message', models.CharField(max_length=100, verbose_name='Message')),
                ('message_long', models.TextField(verbose_name='Message long')),
            ],
        ),
    ]
