# Generated by Django 3.2 on 2021-07-21 13:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frontend', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Reklama',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Reklama nomi')),
                ('img', models.ImageField(max_length=255, upload_to='', verbose_name='Rasim')),
                ('link', models.CharField(max_length=255, verbose_name='Link reklama')),
            ],
        ),
    ]
