# Generated by Django 3.2 on 2021-07-21 18:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('frontend', '0002_reklama'),
    ]

    operations = [
        migrations.RenameField(
            model_name='reklama',
            old_name='img',
            new_name='image',
        ),
    ]
