# Generated by Django 3.2 on 2021-07-31 08:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('frontend', '0003_rename_img_reklama_image'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='livemessage',
            options={'verbose_name': 'Xabar', 'verbose_name_plural': 'Xabarlar'},
        ),
        migrations.AlterModelOptions(
            name='reklama',
            options={'verbose_name': 'Reklama', 'verbose_name_plural': 'Reklamalar'},
        ),
        migrations.RenameField(
            model_name='reklama',
            old_name='link',
            new_name='link_add',
        ),
    ]
