# Generated by Django 3.2 on 2021-04-22 09:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Sections',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120, verbose_name="Bo'lim nomi")),
            ],
        ),
        migrations.CreateModel(
            name='Equipments',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Uskuna nomi')),
                ('new_price', models.FloatField(default=0, verbose_name='Yangi narxi')),
                ('old_price', models.FloatField(default=0, verbose_name='Oldingi narxi')),
                ('new', models.BooleanField(verbose_name='Yangi mahsulot')),
                ('sale', models.IntegerField(default=0, verbose_name='Chegirma')),
                ('info_text', models.TextField(verbose_name="Mahsulot haqida To'liq")),
                ('tg_link', models.CharField(max_length=100, verbose_name='Telegram link')),
                ('ins_link', models.CharField(blank=True, max_length=100, null=True, verbose_name='Instagram link')),
                ('phone', models.CharField(max_length=100, verbose_name='Telifon raqami')),
                ('image', models.ImageField(upload_to='', verbose_name='Rasim')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='technique.sections')),
            ],
        ),
    ]
