# Generated by Django 3.2 on 2021-04-26 09:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sellers', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='market',
            old_name='category',
            new_name='bazar',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='company',
            new_name='market',
        ),
        migrations.AddField(
            model_name='product',
            name='bazar',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='sellers.bazar'),
            preserve_default=False,
        ),
    ]
