# Generated by Django 3.2 on 2021-04-26 09:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sellers', '0002_auto_20210426_1429'),
    ]

    operations = [
        migrations.AddField(
            model_name='market',
            name='image',
            field=models.ImageField(default=1, upload_to='', verbose_name='Rasim'),
            preserve_default=False,
        ),
    ]
