# Generated by Django 3.2 on 2021-04-29 08:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sellers', '0003_alter_market_bazar'),
    ]

    operations = [
        migrations.AlterField(
            model_name='market',
            name='bazar',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='sellers.bazar'),
        ),
    ]
