# Generated by Django 3.2 on 2021-04-29 10:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sellers', '0004_alter_market_bazar'),
    ]

    operations = [
        migrations.AddField(
            model_name='market',
            name='phone2',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Telefon'),
        ),
    ]
