# Generated by Django 3.2 on 2021-07-26 08:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sellers', '0007_alter_product_market'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Ism')),
                ('phone', models.CharField(max_length=255, verbose_name='Telefon')),
                ('province', models.CharField(max_length=50, verbose_name='Viloyat')),
                ('count_product', models.IntegerField(default=0, verbose_name='Mahsulot soni')),
                ('product_name', models.CharField(blank=True, max_length=255, null=True, verbose_name='Mahsulot nomi')),
                ('price', models.CharField(blank=True, max_length=255, null=True, verbose_name='Mahsulot narxi')),
            ],
        ),
    ]
