# Generated by Django 3.2 on 2021-09-03 14:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sellers', '0008_order'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ad_product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Mahsulot nomi')),
                ('new_price', models.FloatField(default=0, verbose_name='Yangi narxi')),
                ('old_price', models.FloatField(default=0, verbose_name='Oldingi narxi')),
                ('info_text', models.TextField(verbose_name="Mahsulot haqida To'liq")),
                ('image', models.ImageField(upload_to='', verbose_name='Rasim')),
                ('size', models.CharField(max_length=200, verbose_name="O'lchami")),
            ],
        ),
        migrations.AlterModelOptions(
            name='bazar',
            options={'verbose_name': 'Bozor', 'verbose_name_plural': 'Bozorlar'},
        ),
        migrations.AlterModelOptions(
            name='market',
            options={'verbose_name': "Do'kon", 'verbose_name_plural': "Do'konlar"},
        ),
        migrations.AlterModelOptions(
            name='order',
            options={'verbose_name': 'Buyurtma', 'verbose_name_plural': 'Buyurtmalar'},
        ),
        migrations.AlterModelOptions(
            name='product',
            options={'verbose_name': 'Mahsulot', 'verbose_name_plural': 'Mahsulotlar'},
        ),
        migrations.AlterField(
            model_name='bazar',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='market',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='order',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='product',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
