# Generated by Django 3.2 on 2021-09-12 08:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sellers', '0010_auto_20210912_1303'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='new_p',
        ),
        migrations.AddField(
            model_name='ad_product',
            name='new_p',
            field=models.BooleanField(default=True, verbose_name='Yangi'),
        ),
    ]
