# Generated by Django 3.2 on 2021-09-26 09:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sellers', '0011_auto_20210912_1359'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='color',
            field=models.CharField(blank=True, max_length=250, null=True, verbose_name='Rangi'),
        ),
        migrations.AddField(
            model_name='order',
            name='size',
            field=models.CharField(default=1, max_length=250, verbose_name="O'lchami"),
            preserve_default=False,
        ),
    ]
