# Generated by Django 3.2 on 2021-06-07 06:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='House',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_company', models.CharField(max_length=255, verbose_name='Studia nomi')),
                ('name_product', models.CharField(max_length=255, verbose_name='Mahsulot nomi')),
                ('content', models.TextField(verbose_name='Studio haqida malumot va ximztlar')),
                ('tg_link', models.CharField(blank=True, max_length=255, null=True, verbose_name='Telegram link')),
                ('ins_link', models.CharField(blank=True, max_length=255, null=True, verbose_name='Instagram link')),
                ('web_site', models.CharField(blank=True, max_length=255, null=True, verbose_name='Web sayt')),
                ('phone', models.CharField(max_length=255, verbose_name='Telefon raqam')),
                ('image', models.ImageField(blank=True, null=True, upload_to='', verbose_name='Rasim')),
                ('image2', models.ImageField(blank=True, null=True, upload_to='', verbose_name='Rasim2')),
                ('image3', models.ImageField(blank=True, null=True, upload_to='', verbose_name='Rasim3')),
                ('image4', models.ImageField(blank=True, null=True, upload_to='', verbose_name='Rasim4')),
                ('image5', models.ImageField(blank=True, null=True, upload_to='', verbose_name='Rasim5')),
                ('image6', models.ImageField(blank=True, null=True, upload_to='', verbose_name='Rasim6')),
                ('image7', models.ImageField(blank=True, null=True, upload_to='', verbose_name='Rasim7')),
                ('image8', models.ImageField(blank=True, null=True, upload_to='', verbose_name='Rasim8')),
                ('image9', models.ImageField(blank=True, null=True, upload_to='', verbose_name='Rasim9')),
                ('image10', models.ImageField(blank=True, null=True, upload_to='', verbose_name='Rasim10')),
            ],
            options={
                'ordering': ['-id'],
            },
        ),
    ]
