# Generated by Django 3.2 on 2021-05-15 07:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SMM',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_studio', models.CharField(max_length=255, verbose_name='Studia nomi')),
                ('name_product', models.CharField(max_length=255, verbose_name='Mahsulot nomi')),
                ('content', models.TextField(verbose_name='Studio haqida malumot va ximztlar')),
                ('tg_link', models.CharField(max_length=255, verbose_name='Telegram link')),
                ('phone', models.CharField(max_length=255, verbose_name='Telefon raqam')),
            ],
        ),
    ]
