# Generated by Django 3.2 on 2021-05-15 07:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('smm', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='smm',
            name='image',
            field=models.ImageField(default=1, upload_to='', verbose_name='Rasim'),
            preserve_default=False,
        ),
    ]
