# Generated by Django 3.2 on 2021-06-03 12:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('smm', '0003_auto_20210515_1631'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='smm',
            options={'ordering': ['-id']},
        ),
        migrations.AddField(
            model_name='smm',
            name='image10',
            field=models.ImageField(blank=True, null=True, upload_to='', verbose_name='Rasim10'),
        ),
        migrations.AddField(
            model_name='smm',
            name='image2',
            field=models.ImageField(blank=True, null=True, upload_to='', verbose_name='Rasim2'),
        ),
        migrations.AddField(
            model_name='smm',
            name='image3',
            field=models.ImageField(blank=True, null=True, upload_to='', verbose_name='Rasim3'),
        ),
        migrations.AddField(
            model_name='smm',
            name='image4',
            field=models.ImageField(blank=True, null=True, upload_to='', verbose_name='Rasim4'),
        ),
        migrations.AddField(
            model_name='smm',
            name='image5',
            field=models.ImageField(blank=True, null=True, upload_to='', verbose_name='Rasim5'),
        ),
        migrations.AddField(
            model_name='smm',
            name='image6',
            field=models.ImageField(blank=True, null=True, upload_to='', verbose_name='Rasim6'),
        ),
        migrations.AddField(
            model_name='smm',
            name='image7',
            field=models.ImageField(blank=True, null=True, upload_to='', verbose_name='Rasim7'),
        ),
        migrations.AddField(
            model_name='smm',
            name='image8',
            field=models.ImageField(blank=True, null=True, upload_to='', verbose_name='Rasim8'),
        ),
        migrations.AddField(
            model_name='smm',
            name='image9',
            field=models.ImageField(blank=True, null=True, upload_to='', verbose_name='Rasim9'),
        ),
        migrations.AlterField(
            model_name='smm',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='', verbose_name='Rasim'),
        ),
    ]
