# Generated by Django 3.2 on 2021-09-10 14:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('smm', '0004_auto_20210603_1757'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='smm',
            name='image10',
        ),
        migrations.RemoveField(
            model_name='smm',
            name='image2',
        ),
        migrations.RemoveField(
            model_name='smm',
            name='image3',
        ),
        migrations.RemoveField(
            model_name='smm',
            name='image4',
        ),
        migrations.RemoveField(
            model_name='smm',
            name='image5',
        ),
        migrations.RemoveField(
            model_name='smm',
            name='image6',
        ),
        migrations.RemoveField(
            model_name='smm',
            name='image7',
        ),
        migrations.RemoveField(
            model_name='smm',
            name='image8',
        ),
        migrations.RemoveField(
            model_name='smm',
            name='image9',
        ),
    ]
