# Generated by Django 3.2 on 2021-09-10 15:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('smm', '0005_auto_20210910_1921'),
    ]

    operations = [
        migrations.AddField(
            model_name='smm',
            name='content_mini',
            field=models.TextField(default=1, verbose_name='Studio haqida malumot'),
            preserve_default=False,
        ),
    ]
