# Generated by Django 3.2 on 2021-04-17 06:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Korxona nomi')),
                ('info', models.CharField(max_length=100, verbose_name='Korxona haqida')),
                ('tg_link', models.CharField(max_length=100, verbose_name='Telegram link')),
                ('ins_link', models.CharField(blank=True, max_length=100, null=True, verbose_name='Telegram link')),
                ('phone', models.CharField(max_length=100, verbose_name='Telifon raqami')),
                ('image', models.ImageField(upload_to='', verbose_name='Rasim')),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Mahsulot nomi')),
                ('new_price', models.FloatField(default=0, verbose_name='Yangi narxi')),
                ('old_price', models.FloatField(default=0, verbose_name='Eski narxi')),
                ('new', models.BooleanField(verbose_name='Yangi mahsulot')),
                ('sale', models.IntegerField(default=0, verbose_name='Chegirma')),
                ('info', models.CharField(max_length=500, verbose_name='Mahsulot haqida')),
                ('tg_link', models.CharField(max_length=100, verbose_name='Telegram link')),
                ('ins_link', models.CharField(blank=True, max_length=100, null=True, verbose_name='Telegram link')),
                ('phone', models.CharField(max_length=100, verbose_name='Telifon raqami')),
                ('image', models.ImageField(upload_to='', verbose_name='Rasim')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shop.company')),
            ],
        ),
    ]
