# Generated by Django 3.2 on 2021-04-08 07:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Korxona nomi')),
                ('info', models.CharField(max_length=100, verbose_name='Korxona haqida')),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Mahsulot nomi')),
                ('info', models.CharField(max_length=500, verbose_name='Mahsulot haqida')),
                ('tg_link', models.CharField(max_length=100, verbose_name='Telegram link')),
                ('phone', models.CharField(max_length=100, verbose_name='Telifon raqami')),
                ('image', models.ImageField(upload_to='', verbose_name='Rasim')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shop.company')),
            ],
        ),
    ]
