# Generated by Django 3.2 on 2021-04-17 06:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0002_alter_product_ins_link'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='info',
            field=models.TextField(max_length=100, verbose_name='Korxona haqida'),
        ),
    ]
