# Generated by Django 3.2 on 2021-04-17 09:21

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0004_alter_company_ins_link'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='name_long',
            field=models.CharField(default=django.utils.timezone.now, max_length=500, verbose_name="Korxona To'liq nomi"),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='product',
            name='info_text',
            field=models.TextField(default=1, verbose_name="Mahsulot haqida To'liq"),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='product',
            name='info',
            field=models.CharField(max_length=500, verbose_name='Mahsulot haqida qisqa'),
        ),
    ]
