# Generated by Django 3.2 on 2021-04-19 05:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0005_auto_20210417_1421'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='info',
            field=models.TextField(verbose_name='Korxona haqida'),
        ),
    ]
