# Generated by Django 3.2 on 2021-04-22 09:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0006_alter_company_info'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='info',
            field=models.CharField(max_length=100, verbose_name='Mahsulot haqida qisqa'),
        ),
    ]
