# Generated by Django 3.2 on 2021-05-03 08:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Categorys',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250, verbose_name='Toifa nomi')),
            ],
        ),
        migrations.CreateModel(
            name='Clinics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250, verbose_name='Klinika nomi')),
                ('info_service', models.CharField(max_length=500, verbose_name='Xizmatlar')),
                ('tg_link', models.CharField(max_length=200, verbose_name='Telegram link')),
                ('locations', models.CharField(max_length=200, verbose_name='Klinika manzili')),
                ('info_long', models.TextField(verbose_name='Klinika haqida to‘liq maʼlumot')),
                ('phone', models.CharField(max_length=50, verbose_name='Telefon')),
                ('phone2', models.CharField(blank=True, max_length=50, null=True, verbose_name='Ikkinchi telefon raqam ')),
                ('image', models.ImageField(upload_to='', verbose_name='Rasim')),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='products', to='clinics.categorys')),
            ],
        ),
    ]
