# Generated by Django 3.2 on 2021-05-06 06:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Pharmacy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Dori nomi')),
                ('pharmacy_info', models.CharField(max_length=400, verbose_name='Dori haqida qisqacha')),
                ('tg_link', models.CharField(max_length=200, verbose_name='Telegram link')),
                ('ins_link', models.CharField(max_length=200, verbose_name='Instagram link')),
                ('new_price', models.FloatField(default=0, verbose_name='Yangi narxi')),
                ('old_price', models.FloatField(default=0, verbose_name='Oldingi narxi')),
                ('new', models.BooleanField(verbose_name='Yangi mahsulot')),
                ('sale', models.IntegerField(default=0, verbose_name='Chegirma')),
                ('content', models.TextField(verbose_name="To'lqi malumot")),
                ('phone', models.CharField(max_length=50, verbose_name='Telefon')),
                ('phone2', models.CharField(blank=True, max_length=50, null=True, verbose_name='Telefon')),
                ('image', models.ImageField(upload_to='', verbose_name='Rasim')),
                ('locations', models.CharField(max_length=200, verbose_name='Dorixona  manzili')),
            ],
        ),
    ]
