# Generated by Django 3.2 on 2021-05-09 11:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pharmacies', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Ism')),
                ('phone', models.CharField(max_length=255, verbose_name='Telefon')),
                ('province', models.CharField(choices=[('TSH', 'Toshkent shahri'), ('TV', 'Toshkent viloyati'), ('AND', 'Andijon'), ('BUX', 'Buxoro'), ('FAR', "Farg'ona"), ('JIZ', 'Jizzax'), ('NAM', 'Namangan'), ('NAV', 'Navoiy'), ('QASH', 'Qashqadaryo'), ('QQ', "Qoraqalpog'iston"), ('SAM', 'Samarqand'), ('SIR', 'Sirdaryo'), ('SUR', 'Surxondaryo'), ('XOR', 'Xorazm')], default='TSH', max_length=4)),
                ('count_product', models.IntegerField(default=0, verbose_name='Mahsulot soni')),
            ],
        ),
    ]
