# Generated by Django 3.2 on 2021-05-09 12:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pharmacies', '0002_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='product_name',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Mahsulot nomi'),
        ),
        migrations.AddField(
            model_name='order',
            name='shop_name',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Korxona nomi'),
        ),
    ]
