# Generated by Django 3.2 on 2021-05-10 11:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pharmacies', '0004_alter_order_province'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='shop_name',
            new_name='price',
        ),
    ]
