# Generated by Django 3.2 on 2021-06-03 18:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pharmacies', '0005_rename_shop_name_order_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='price',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Mahsulot narxi'),
        ),
    ]
